#!/usr/bin/env python3
"""
gen_compiler.py — Generator for preamble.re, compiler_sf.re, and aria/layout.re

Responsibilities:
  1. Read preamble_template.ll, substitute Aether layout constants,
     and pack the result as PREAM_* Lux byte chains in preamble.re.
  2. Write aria/layout.re with Aether aether layout constants.
  3. Generate compiler_sf.re with XLEN-dependent SF_* string values.
     (XI.2 fix: replaces regex-patching of yaku.re with a generated file.)
  4. Call freeze() to rebuild reca.bin.

Python is a BLIND ASSEMBLER here. It does NOT know LLVM IR semantics.
The IR lives in preamble_template.ll — edit that file, not this one.

XI.2 fix — single source of truth for XLEN-dependent SF_* strings:
  Previously gen_compiler.py used regex to patch SET lines inside yaku.re.
  This was fragile (regex on .re source) and split the SF_* "value" across
  two files (hardcoded stub in yaku.re + correct value in gen_compiler.py).
  Now:
    yaku.re   declares NEW SF_*  (name + no value — word stays 0 until SET)
    compiler_sf.re (generated here) provides SET SF_* with correct XLEN values
  Changing XLEN requires editing symphony.py (XLEN constant) and re-running gen_compiler.py.

Usage:
  python3 gen_compiler.py          # writes preamble.re + compiler_sf.re + aria/layout.re + reca.bin
  python3 gen_compiler.py --check  # prints first 20 lines of preamble, does not write
"""
import os
import sys

_HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, _HERE)

from symphony import AETHER_SIZE, XLEN

# Aria convention: these three luces are reserved by layout.re for
# bookkeeping. Python does not know about them — gen_compiler hardcodes
# them ONLY when generating aria/layout.re (which is itself an aria file).
# Everywhere else (Python interpreter, freeze logic) sees them as ordinary
# luces. They live here as the single source of truth.
_K_CURSOR_LUX    = 1   # aether[1] = current bump position
_K_WATERMARK_LUX = 2   # aether[2] = high-water mark (max addr touched)
_K_TRACE_POS_LUX = 3   # aether[3] = trace write pos (0 = tracing off)

_TEMPLATE = os.path.join(_HERE, 'preamble_template.ll')


def _build_preamble() -> str:
    """
    Read preamble_template.ll, substitute Aether layout constants.
    Python does not interpret the IR — it only replaces {{PLACEHOLDER}} markers.
    """
    with open(_TEMPLATE, 'r', encoding='utf-8') as f:
        text = f.read()

    # Strip comments (lines starting with ;) — they are documentation,
    # not part of the emitted IR
    lines = [ln for ln in text.split('\n') if not ln.lstrip().startswith(';')]
    text = '\n'.join(lines).strip() + '\n'

    substitutions = {
        '{{TOTAL_SIZE}}':           str(AETHER_SIZE),
        '{{ALLOC_PTR_ADDR}}':       str(_K_CURSOR_LUX),    # cursor lux
        '{{K_CURSOR_LUX}}':        str(_K_CURSOR_LUX),
        '{{K_WATERMARK_LUX}}':     str(_K_WATERMARK_LUX),
    }
    for placeholder, value in substitutions.items():
        text = text.replace(placeholder, value)

    return text


def _pack_bytes(text: str) -> list:
    raw = text.encode('ascii')
    result = []
    for i in range(0, len(raw), 8):
        chunk = raw[i:i + 8]
        word = 0
        for j, b in enumerate(chunk):
            word |= (b << (j * 8))
        result.append(word)
    result.append(0)
    return result


def _build_compiler_sf(xlen: int) -> list:
    """
    Build compiler_sf.re content: SET SF_* strings for the given XLEN.

    Single source of truth for XLEN-dependent SF_* values (XI.2 fix).
    yaku.re declares NEW SF_* (name only, word=0 until this file sets it).
    compiler_sf.re is loaded after yaku.re (compile ordering: compiler_sf.re
    references SF_* names defined in yaku.re, so it compiles after it).
    """
    lines = [
        '// compiler_sf.re — GENERATED by gen_compiler.py. DO NOT EDIT. //',
        f'// XLEN-dependent SF_* string values for XLEN={xlen}. //',
        '// Regenerate: python3 gen_compiler.py //',
        '// yaku.re declares NEW SF_* — this file provides the SET values. //',
        '// Yaku order: compiler_sf.re references SF_* names from yaku.re, //',
        '// so it is automatically loaded after yaku.re by Saku. //',
        '',
    ]

    sf_values = [
        ('SF_X_I64',
            f' x i{xlen}] zeroinitializer\\n'),
        ('SF_FUNCOPEN',
            f'define i{xlen} @'),
        ('SF_GEP_MID',
            f' x i{xlen}], ptr @heap, i{xlen} 0, i{xlen} '),
        # SF_LOAD_SFX removed — superseded by SF_LOAD_IGEP_PRE inline GEP
        ('SF_JR_LOAD',
            f'  %jr_t = load i{xlen}, ptr @jr_slot\\n'
            f'  switch i{xlen} %jr_t, label %L_jrerr [\\n'),
        ('SF_JR_ARM_PFX',
            f'    i{xlen} '),
        ('SF_JR_TAIL',
            f'  ]\\nL0:\\n  ret i{xlen} 0\\nL_jrerr:\\n  ret i{xlen} 0\\n'),
    ]

    for sf_name, value in sf_values:
        lines.append(f'SET {sf_name} "{value}"')

    lines.append('')
    return lines




# ── main ──────────────────────────────────────────────────────────────────────
check_only = '--check' in sys.argv

out = []
out.append('// preamble.re — GENERATED by gen_compiler.py. DO NOT EDIT. //')
out.append('// PREAM_* Lux: packed LLVM IR helpers from preamble_template.ll. //')
out.append('// Regenerate: python3 gen_compiler.py //')
out.append('')
out.append('// ── PREAM_* Lux ──────────────────────────────────────────────────────────//')

preamble_text = _build_preamble()
packed = _pack_bytes(preamble_text)

for i, word in enumerate(packed):
    out.append(f'NEWSET PREAM_{i:04d} {word}')

out.append('')
out.append(f'// PREAM stats: {len(preamble_text)} bytes -> {len(packed)} Lux //')
out.append('')

total_lines = len(out)

if check_only:
    for line in out[:20]:
        print(line)
    print(f'Total: {total_lines} lines, {len(packed)} PREAM Lux')
    sys.exit(0)

# Write aria/layout.re
layout_path = os.path.join(_HERE, 'aria', 'layout.re')
os.makedirs(os.path.dirname(layout_path), exist_ok=True)
layout_lines = [
    '// aria/layout.re — Aether layout constants. Generated by gen_compiler.py. DO NOT EDIT. //',
    '// Canon: K_CURSOR.word=1 (bump pos), K_WATERMARK.word=2 (high-water), K_TRACE_POS.word=3 (trace). //',
    '',
]
for lname, lval, lcomment in [
    ('K_CURSOR',         _K_CURSOR_LUX,    'address of cursor lux (current bump position lives there)'),
    ('K_WATERMARK',      _K_WATERMARK_LUX, 'address of watermark lux (max addr touched lives there)'),
    ('K_TRACE_POS',      _K_TRACE_POS_LUX, 'address of trace-pos lux (0 = tracing off)'),
    ('K_AETHER_SIZE',    AETHER_SIZE,       'total Aether array size in luces'),
    ('K_XLEN',           XLEN,              'target word width in bits'),
]:
    layout_lines.append(f'NEWSET {lname} {lval}')
layout_lines.append('')
with open(layout_path, 'w') as lf:
    lf.write('\n'.join(layout_lines))
print(f'Wrote {layout_path}', file=sys.stderr)

# Write preamble.re
out_path = os.path.join(_HERE, 'preamble.re')
with open(out_path, 'w') as f:
    f.write('\n'.join(out) + '\n')
print(f'Wrote {out_path}: {total_lines} lines ({len(packed)} PREAM Lux)',
      file=sys.stderr)

# Write compiler_sf.re (XI.2 fix: replaces regex patching of yaku.re)
sf_lines = _build_compiler_sf(XLEN)
sf_path = os.path.join(_HERE, 'compiler_sf.re')
with open(sf_path, 'w') as f:
    f.write('\n'.join(sf_lines) + '\n')
print(f'Wrote {sf_path} (XLEN={XLEN})', file=sys.stderr)

# Freeze
# (rule_graphs.re removed: RO_* graphs are now built inline by loader.py during freeze)
from loader import freeze as _do_freeze, _BIN as _BIN
_do_freeze()

# Generate reca_init.ll from the freshly frozen bin.
# This is the authoritative static initialiser for the compiled binary:
# it captures the clean Aether state (all Lux words, all Lumen, all system
# luces) exactly as it exists after freeze — before any runtime execution.
# yaku.re's EMIT_INIT_FUNC is removed; reca_init() now comes from here.
def _build_reca_init_ll() -> str:
    from symphony import Aether, AETHER_SIZE, XLEN as _XLEN
    s = Aether()
    s.thaw(_BIN)
    a = s.aether
    # Read the high-water mark from the lux K_WATERMARK points to.
    # This is aria convention (K_WATERMARK.word = K_WATERMARK_LUX = 2),
    # so we know it lives at aether[_K_WATERMARK_LUX] after freeze.
    used = a[_K_WATERMARK_LUX] + 1 if a[_K_WATERMARK_LUX] > 0 else len(a)

    lines: list[str] = []
    lines.append('define void @reca_init() {')
    lines.append('entry:')

    # Emit store for every nonzero lux in used region.
    # New layout is much smaller (no pool), so this is fast.
    for idx in range(used):
        v = a[idx]
        if v == 0:
            continue
        lines.append(
            f'  store i{_XLEN} {v}, '
            f'ptr getelementptr inbounds ([{AETHER_SIZE} x i{_XLEN}], '
            f'ptr @heap, i{_XLEN} 0, i{_XLEN} {idx})'
        )

    lines.append('  ret void')
    lines.append('}')
    lines.append('')
    return '\n'.join(lines)


_ri_path = os.path.join(_HERE, 'reca_init.ll')
_ri_text = _build_reca_init_ll()
with open(_ri_path, 'w') as _f:
    _f.write(_ri_text)
_nz = _ri_text.count('\n  store')
print(f'Wrote {_ri_path}: {_nz} store instructions', file=sys.stderr)
