#!/usr/bin/env python3
"""
gen_compiler.py — Generator for generated/{preamble,compiler_sf,layout}.re

Responsibilities:
  1. Read preamble_template.ll, substitute Aether layout constants,
     and pack the result as PREAM_* Lux byte chains in preamble.re.
  2. Write generated/layout.re with Aether layout constants (K_XLEN, K_AETHER_SIZE).
  3. Generate compiler_sf.re with XLEN-dependent SF_* string values.
     (XI.2 fix: replaces regex-patching of yaku.re with a generated file.)

Python is a BLIND ASSEMBLER here. It does NOT know LLVM IR semantics.
The IR lives in preamble_template.ll — edit that file, not this one.

XI.2 fix — single source of truth for XLEN-dependent SF_* strings:
  Previously gen_compiler.py used regex to patch SET lines inside yaku.re.
  This was fragile (regex on .re source) and split the SF_* "value" across
  two files (hardcoded stub in yaku.re + correct value in gen_compiler.py).
  Now:
    yaku.re   declares NEW SF_*  (name + no value — word stays 0 until SET)
    compiler_sf.re (generated here) provides SET SF_* with correct XLEN values
  Changing XLEN requires editing symphony.py (XLEN constant) and re-running.

Usage (standalone):
  python3 gen_compiler.py          # generate files + freeze + reca_init.ll
  python3 gen_compiler.py --check  # print first 20 lines of preamble, no writes
  python3 gen_compiler.py --no-freeze  # generate files only, skip freeze

Usage (from loader.py / freeze()):
  import gen_compiler; gen_compiler.generate_artifacts()
  Generates generated/layout.re, generated/preamble.re, generated/compiler_sf.re.
  freeze() is called by loader.py itself after generate_artifacts() returns.
"""
import os
import sys

_HERE = os.path.dirname(os.path.abspath(__file__))
# If this file is in a subdirectory (e.g. tooling/), root is one level up.
# Marker: loader.py lives at the project root.
_ROOT = _HERE if os.path.exists(os.path.join(_HERE, 'symphony.py')) else os.path.dirname(_HERE)

sys.path.insert(0, _ROOT)

from symphony import AETHER_SIZE, XLEN

_TEMPLATE = os.path.join(_ROOT, 'preamble_template.ll')


def _build_preamble() -> str:
    """
    Read preamble_template.ll, substitute Aether layout constants.
    Python does not interpret the IR — it only replaces {{PLACEHOLDER}} markers.
    """
    with open(_TEMPLATE, 'r', encoding='utf-8') as f:
        text = f.read()

    # Strip comments (lines starting with ;) — they are documentation,
    # not part of the emitted IR
    lines = [ln for ln in text.split('\n') if not ln.lstrip().startswith(';')]
    text = '\n'.join(lines).strip() + '\n'

    substitutions = {
        '{{TOTAL_SIZE}}':      str(AETHER_SIZE),
        '{{ALLOC_PTR_ADDR}}':  '1',   # K_CURSOR lives at aether[1] (alloc.re NEW K_CURSOR)
        '{{K_CURSOR_LUX}}':    '1',
        '{{K_WATERMARK_LUX}}': '2',
    }
    for placeholder, value in substitutions.items():
        text = text.replace(placeholder, value)

    return text


def _pack_bytes(text: str) -> list:
    raw = text.encode('ascii')
    result = []
    for i in range(0, len(raw), 8):
        chunk = raw[i:i + 8]
        word = 0
        for j, b in enumerate(chunk):
            word |= (b << (j * 8))
        result.append(word)
    result.append(0)
    return result


def _build_compiler_sf(xlen: int) -> list:
    """
    Build compiler_sf.re content: SET SF_* strings for the given XLEN.

    Single source of truth for XLEN-dependent SF_* values (XI.2 fix).
    yaku.re declares NEW SF_* (name only, word=0 until this file sets it).
    compiler_sf.re is loaded after yaku.re (compile ordering: compiler_sf.re
    references SF_* names defined in yaku.re, so it compiles after it).
    """
    lines = [
        '// compiler_sf.re — GENERATED by gen_compiler.py. DO NOT EDIT. //',
        f'// XLEN-dependent SF_* string values for XLEN={xlen}. //',
        '// Regenerate: python3 gen_compiler.py //',
        '// yaku.re declares NEW SF_* — this file provides the SET values. //',
        '// Yaku order: compiler_sf.re references SF_* names from yaku.re, //',
        '// so it is automatically loaded after yaku.re by Saku. //',
        '',
    ]

    sf_values = [
        ('SF_X_I64',
            f' x i{xlen}] zeroinitializer\\n'),
        ('SF_FUNCOPEN',
            f'define i{xlen} @'),
        ('SF_GEP_MID',
            f' x i{xlen}], ptr @heap, i{xlen} 0, i{xlen} '),
        ('SF_JR_LOAD',
            f'  %jr_t = load i{xlen}, ptr @jr_slot\\n'
            f'  switch i{xlen} %jr_t, label %L_jrerr [\\n'),
        ('SF_JR_ARM_PFX',
            f'    i{xlen} '),
        ('SF_JR_TAIL',
            f'  ]\\nL0:\\n  ret i{xlen} 0\\nL_jrerr:\\n  ret i{xlen} 0\\n'),
    ]

    for sf_name, value in sf_values:
        lines.append(f'SET {sf_name} "{value}"')

    lines.append('')
    return lines


def generate_artifacts(verbose: bool = True) -> None:
    """Generate layout.re, preamble.re, compiler_sf.re from current symphony.py constants.

    Called by loader.py freeze() before loading .re files, so that
    aria/layout.re (K_XLEN, K_AETHER_SIZE) is always up to date.

    Does NOT call freeze() — the caller (loader.py) does that.
    Does NOT generate reca_init.ll — that requires a frozen binary.
    """
    def _log(msg):
        if verbose:
            print(msg, file=sys.stderr)

    # aria/layout.re — K_AETHER_SIZE and K_XLEN only.
    # K_CURSOR/K_WATERMARK/K_TRACE_POS/K_STACK_TOP live in alloc.re.
    layout_path = os.path.join(_ROOT, 'generated', 'layout.re')
    os.makedirs(os.path.dirname(layout_path), exist_ok=True)
    layout_lines = [
        '// aria/layout.re — Aether layout constants. Generated by gen_compiler.py. DO NOT EDIT. //',
        '// K_AETHER_SIZE and K_XLEN are the only constants here. //',
        '// K_CURSOR/K_WATERMARK/K_TRACE_POS/K_STACK_TOP live in alloc.re (runtime). //',
        '',
    ]
    for lname, lval in [
        ('K_AETHER_SIZE', AETHER_SIZE),
        ('K_XLEN',        XLEN),
    ]:
        layout_lines.append(f'NEWSET {lname} {lval}')
    layout_lines.append('')
    with open(layout_path, 'w') as lf:
        lf.write('\n'.join(layout_lines))
    _log(f'Wrote {layout_path}')

    # preamble.re — packed LLVM IR preamble
    preamble_text = _build_preamble()
    packed = _pack_bytes(preamble_text)
    out = [
        '// preamble.re — GENERATED by gen_compiler.py. DO NOT EDIT. //',
        '// PREAM_* Lux: packed LLVM IR helpers from preamble_template.ll. //',
        '// Regenerate: python3 gen_compiler.py //',
        '',
        '// ── PREAM_* Lux ──────────────────────────────────────────────────────────//',
    ]
    for i, word in enumerate(packed):
        out.append(f'NEWSET PREAM_{i:04d} {word}')
    out.append('')
    out.append(f'// PREAM stats: {len(preamble_text)} bytes -> {len(packed)} Lux //')
    out.append('')
    out_path = os.path.join(_ROOT, 'generated', 'preamble.re')
    with open(out_path, 'w') as f:
        f.write('\n'.join(out) + '\n')
    _log(f'Wrote {out_path}: {len(out)} lines ({len(packed)} PREAM Lux)')

    # compiler_sf.re — XLEN-dependent SF_* strings
    sf_lines = _build_compiler_sf(XLEN)
    sf_path = os.path.join(_ROOT, 'generated', 'compiler_sf.re')
    with open(sf_path, 'w') as f:
        f.write('\n'.join(sf_lines) + '\n')
    _log(f'Wrote {sf_path} (XLEN={XLEN})')


def _needs_regen() -> bool:
    """Return True if generated files are missing or older than symphony.py."""
    symphony_mtime = os.path.getmtime(os.path.join(_ROOT, 'symphony.py'))
    targets = [
        os.path.join(_ROOT, 'generated', 'layout.re'),
        os.path.join(_ROOT, 'generated', 'preamble.re'),
        os.path.join(_ROOT, 'generated', 'compiler_sf.re'),
    ]
    for t in targets:
        if not os.path.exists(t):
            return True
        if os.path.getmtime(t) < symphony_mtime:
            return True
    return False


# ── main ──────────────────────────────────────────────────────────────────────
if __name__ == '__main__':
    if '--check' in sys.argv:
        preamble_text = _build_preamble()
        packed = _pack_bytes(preamble_text)
        out = ['// preamble.re preview (first 20 lines):']
        for i, word in enumerate(packed[:18]):
            out.append(f'NEWSET PREAM_{i:04d} {word}')
        for line in out:
            print(line)
        print(f'Total: {len(packed)} PREAM Lux, {len(preamble_text)} bytes')
        sys.exit(0)

    generate_artifacts(verbose=True)

    if '--no-freeze' not in sys.argv:
        # Full pipeline: freeze + reca_init.ll
        from loader import freeze as _do_freeze, _BIN as _BIN
        _do_freeze()

        # Generate reca_init.ll from the freshly frozen binary.
        # Authoritative static initialiser for the compiled binary.
        from symphony import Aether, AETHER_SIZE as _AS, XLEN as _XLEN
        _K_WATERMARK_LUX = 2
        s = Aether()
        s.thaw(_BIN)
        a = s.aether
        used = a[_K_WATERMARK_LUX] + 1 if a[_K_WATERMARK_LUX] > 0 else len(a)

        lines: list = []
        lines.append('define void @reca_init() {')
        lines.append('entry:')
        for idx in range(used):
            v = a[idx]
            if v == 0:
                continue
            lines.append(
                f'  store i{_XLEN} {v}, '
                f'ptr getelementptr inbounds ([{_AS} x i{_XLEN}], '
                f'ptr @heap, i{_XLEN} 0, i{_XLEN} {idx})'
            )
        lines.append('  ret void')
        lines.append('}')
        lines.append('')

        _ri_path = os.path.join(_ROOT, 'reca_init.ll')
        with open(_ri_path, 'w') as _f:
            _f.write('\n'.join(lines))
        _nz = lines.count('  store')  # faster than counting in text
        print(f'Wrote {_ri_path}: {_nz} store instructions', file=sys.stderr)
